import { headers } from 'next/headers'
import Link from 'next/link'
import Footer from '@/components/Footer'

export default async function DisclaimerPage() {
  const headersList = await headers()
  const hostname = headersList.get('x-tenant-host') || 'localhost'
  const displayName = hostname.replace(/^www\./, '').split('.')[0]
  const capitalizedName = displayName.charAt(0).toUpperCase() + displayName.slice(1)

  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-gray-200">
        <div className="mx-auto max-w-4xl px-4 py-6">
          <Link href="/" className="text-xl font-bold text-gray-900">{capitalizedName}</Link>
        </div>
      </header>
      <main className="mx-auto max-w-4xl px-4 py-12">
        <h1 className="mb-8 text-3xl font-bold text-gray-900">Disclaimer</h1>
        <div className="prose prose-gray max-w-none space-y-6 text-gray-700">
          <p><strong>Last Updated:</strong> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

          <h2 className="text-xl font-semibold text-gray-900">1. General Information</h2>
          <p>The assessments, calculators, and tools provided on {capitalizedName} are for informational and educational purposes only. They do not constitute professional advice, recommendations, or endorsements of any kind.</p>

          <h2 className="text-xl font-semibold text-gray-900">2. No Professional Advice</h2>
          <p>The results generated by our assessment tools should not be considered as financial, legal, medical, insurance, or any other form of professional advice. Always consult with qualified professionals before making important decisions.</p>

          <h2 className="text-xl font-semibold text-gray-900">3. Accuracy of Information</h2>
          <p>While we strive to provide accurate and up-to-date information, {capitalizedName} makes no warranties or representations regarding the accuracy, completeness, or reliability of any content or assessment results.</p>

          <h2 className="text-xl font-semibold text-gray-900">4. Third-Party Content</h2>
          <p>Our platform may contain links to third-party websites or display third-party advertisements. We are not responsible for the content, accuracy, or practices of any third-party sites or advertisers.</p>

          <h2 className="text-xl font-semibold text-gray-900">5. Limitation of Liability</h2>
          <p>{capitalizedName} shall not be held liable for any losses, damages, or consequences arising from the use of our assessment tools or reliance on information provided through our platform.</p>
        </div>
      </main>
      <Footer />
    </div>
  )
}
